### ISSUE TITLE
backtrace when calling (amx)

### ISSUE THREAD

**Issue by ArneBab** [DarwinAwardWinner/smex#25]
I often get a backtrace in amx, but not reliably. Also calling amx sometimes degrades to just insert a linebreak. I bound amx to &lt;menu&gt; to avoid shadowing M-x completely: (global-set-key (kbd "&lt;menu&gt;") 'amx)

Here’s a log of breakage: [amx-backtrace.log](https://github.com/DarwinAwardWinner/amx/files/1676875/amx-backtrace.log)

**Comment by DarwinAwardWinner** [comment]
I pushed a fix for this, which passed all the tests on my machine but failed a bunch of tests on Travis, so I had to revert it. I'll investigate more when I have time.

**Comment by ArneBab** [comment]
Thank you for taking it up! Using amx feels awesome and it would be great to have it as primary command selection again. It feels like command selection suddenly comes alive :)

**Comment by ArneBab** [comment]
Thank you very much!
