### ISSUE TITLE
Missing dependecy "ido-completing-read+"?

### ISSUE THREAD

**Issue by luciferasm** [DarwinAwardWinner/smex#27]
Amx doesn't work with ido for me on GNU Emacs 25.3.1. To reproduce:

* Start with a clean `/.emacs.d/elpa/` and `emacs -Q`
*  In \*scratch\*-pad, eval `(setq-default package-archives '(("gnu" . "https://elpa.gnu.org/packages/") ("melpa" . "https://melpa.org/packages/")))`
* `M-x package-install` _\<return\>_ `amx`
* `M-x ido-mode`
* `M-x amx` now produces the error message: **"Feature ‘ido-completing-read+’ is required for backend"**

So, there seem to be a missing dependency `ido-completing-read+` when installing from Melpa.

**Comment by DarwinAwardWinner** [comment]
ido-completing-read+ is an optional dependency, since amx is also usable with normal emacs completion and ivy. I suppose amx should at least produce a warning and fall back to standard emacs completion instead of throwing an error if the optional dependencies aren't met.

**Comment by DarwinAwardWinner** [comment]
This error should now be presented as a warning, and you will get standard emacs completion instead.
