### ISSUE TITLE
M-x enters linebreak when amx is already active in the minibuffer

### ISSUE THREAD

**Issue by ArneBab** [DarwinAwardWinner/smex#29]
Hi,

When I call `M-x` (bound to amx) and then use `C-x o` to switch to another window, using `M-x` again enters a linebreak. 

Expected: 
- Either follow regular `M-x` (execute-extended-command) and show an error in minibuffer "completing-read-default: Command attempted to use minibuffer while in minibuffer",
- or do something more useful, like switching back to the already active amx selection in the minibuffer.

Best wishes,
Arne

PS: as you see, I now have amx active as default `M-x` provider, and it’s awesome! Thank you!

**Comment by DarwinAwardWinner** [comment]
Sure enough, I see the same behavior when I set `enable-recursive-minibuffers` to nil (which is the default). I'll fix this when I get the chance.

**Comment by ArneBab** [comment]
Thank you!
