### ISSUE TITLE
Missing profiler-* commands

### ISSUE THREAD

**Issue by wyuenho** [DarwinAwardWinner/smex#30]
On the NS port, the `profiler-report`, `profiler-stop` etc commands don't show up until you've started the profiler with `profiler-start`. However, the amx cache doesn't seem to update itself after the profiler has started, so M-x profiler- TAB TAB doesn't return `profiler-stop` after starting the profiler.

**Comment by DarwinAwardWinner** [comment]
I assume this has to do with the fact that profiler.el is autoloaded the first time you run `profile-start`?

**Comment by wyuenho** [comment]
That's right. The other commands loaded later don't cause the amx cache to
update it seems.

**Comment by DarwinAwardWinner** [comment]
Can you try running `(advice-add 'autoload-do-load :after #'amx-post-eval-force-update)` and see if that fixes it?

**Comment by wyuenho** [comment]
That fixed it!

**Comment by DarwinAwardWinner** [comment]
Did you make sure to test it after restarting Emacs, so that the file would need to be autoloaded again?

**Comment by wyuenho** [comment]
Yep. It works.
