### ISSUE TITLE
Can't complete based on the keyboard shortcut for counsel-M-x

### ISSUE THREAD

**Issue by floating-cat** [DarwinAwardWinner/smex#35]
The documentation says:
> Alternatively, if you know the keyboard shortcut but don't remember the name of the command it's bound to, you can complete based on the keyboard shortcut (this works best with ido or ivy backends).

The keyboard shortcut completion works fine for ivy, but If I enable `counsel-mode`, this completion doesn't work anymore.
Would amx support `counsel-M-x` or this is the issue should fix in the counsel?

Thanks.

**Comment by DarwinAwardWinner** [comment]
`counsel-M-x` doesn't use amx for completion, so there's nothing amx can do about this. This is an issue with counsel.
