### ISSUE TITLE
Is it possible to have Smex-like completion?

### ISSUE THREAD

**Issue by doublep** [DarwinAwardWinner/smex#37]
With Smex I got used to completion that ignores hyphens. E.g. `M-x killem` would match `kill-emacs` etc. Is it possible to have something similar in Amx? Nothing in `M-x customize-group amx` seems to achieve this.

**Comment by DarwinAwardWinner** [comment]
It depends on what completion method you're using. Presumably you're using the ido backend (it auto-selects based on whether ido-mode is enabled). So you probably want to customize `ido-enable-flex-matching`. 

Smex enables flex matching by default even if it's not enabled for other ido completion (see [here](https://github.com/nonsequitur/smex/blob/master/smex.el#L135)). Amx is completion method-agnostic, so it just uses the settings of the completion backend as is.

**Comment by doublep** [comment]
Perfect, thank you.
