### ISSUE TITLE
Using `completing-read-default` blocks other completion frameworks which use default completion API

### ISSUE THREAD

**Issue by clemera** [DarwinAwardWinner/smex#38]
Could the auto backend fallback to use `completing-read`? This way other completion frameworks like [selectrum](https://github.com/raxod502/selectrum) would automatically work without further configuration. The standard way to configure completion is by setting `completing-read-function` which `completing-read` uses internally.

**Comment by clemera** [comment]
After looking through the code it seems one simple way to fix this would be to use `completing-read` if `amx-backend` is set to `auto` in `amx-completing-read-default` and `completing-read-default` if the backend is set to `standard`. In case of `auto` it would also be better to leave `minibuffer-electric-default-mode` off I guess.

**Comment by DarwinAwardWinner** [comment]
The reason `amx-backend` exists is that setting `completing-read-function` is not by itself sufficient for amx to support a completion method. If support for selectrum is desired, then a backend needs to be written for it.

**Comment by clemera** [comment]
Selectrum just works when using `completing-read` instead of `completing-read-default`. If the framework complies to the default completion API why isn't that sufficient?

**Comment by DarwinAwardWinner** [comment]
For aspects of its functionality, amx needs to know how to do certain things within the completion environment, such as getting the user's currently entered text, or exiting with the current selection. There's no way to auto-detect how to do these based on the value of `completing-read-function`. For instance, compare `amx-default-get-text`, `amx-ido-get-text`, and `amx-ivy-get-text`.

**Comment by clemera** [comment]
I see, rerunning `amx` with `selectrum` does indeed not work out of the box. But the rerun functionality is the only one I see which makes a backend necessary. I still think automatically supporting the features which work for non sophisticated frameworks which don't deter from default behavior for `auto` would be great. I can write a backend for `selectrum` if you like and provide a PR.

**Comment by DarwinAwardWinner** [comment]
It would be great if the auto backend could support the more basic functionality for any value of `completing-read-function` and just disable the features that require additional information from the backend, but again, I don't see a way to do that automatically. If you want to try and develop that and submit it as a PR, I'd be happy to review it. Ultimately though, I don't know if there are enough distinct completion systems implemented for Emacs that such a feature would be worthwhile. It's easy enough to just write a backend for each completion system.

On that subject, a PR adding support for selectrum would be welcome.

**Comment by clemera** [comment]
OK I will wait until my last selectrum [PR](https://github.com/raxod502/selectrum/pull/37) is merged and then write the backend, thanks.

**Comment by clemera** [comment]
Oh and I will better wait until standard history support has landed, so this can be included right away.

**Comment by DarwinAwardWinner** [comment]
I believe this is now fixed by merging #39.
