### ISSUE TITLE
frequently used M-x commands not showing up when moving from smex to amx

### ISSUE THREAD

**Issue by sivaramn** [DarwinAwardWinner/smex#40]
I recently switched from `smex` to `amx` from melpa `ver 3.3`  with the following settings in my config
```
    (require 'amx)
    (setq amx-mode t)
    (setq amx-ignored-command-matchers nil)
    (setq amx-show-key-bindings nil)
    (setq amx-history-length 30)
```

While it works without any issues, it doesn't seem to show the most frequently used commands. when i do ` M-x` the first option i get is `enable-theme` when it should be something like `gnus` or `list-packages` or `dired`.  Though some of them are triggered by keychords.

I had a look at `amex-items` and it doesn't seem right as it has

```
 cd
 5x5
 all
 amx
 arp
 dbx
 dig
 erc
 ert
 eww
 ftp
 gdb
 irc
...
```

Is this expected behaviour? If yes, is there a way to list most used `M-x` commands first?
I check `smex-items` and it has

```
;; ----- smex-history -----
(
 ffap
 rgrep
 reftex-grep-document
 gnus
 occur
 list-packages
 unicode-fonts-setup
 file-cache-add-directory-list
 list-fontsets
 apropos
...
```

sivaram

**Comment by DarwinAwardWinner** [comment]
The history functionality of amx is all inherited from smex, and I haven't touched that code very much, so unfortunately I'm not very familiar with it. However, I'll try to investigate this when I get the chance.

**Comment by DarwinAwardWinner** [comment]
Ok, to help me debug this, do you think you can send me your smex history file to test on? Also, can you try setting `amx-save-file` to a temporary file, then running `(progn (amx-load-save-file) (amx-save-to-file))`? This should load the smex history and then save it to that temporary file. Then send me that file as well.

**Comment by sivaramn** [comment]
> 
> 
> Ok, to help me debug this, do you think you can send me your smex history file to test on? Also, can you try setting `amx-save-file` to a temporary file, then running `(progn (amx-load-save-file) (amx-save-to-file))`? This should load the smex history and then save it to that temporary file. Then send me that file as well.

The problem went away after I restarted the emacs instance
