### ISSUE TITLE
Default candidate argument to completing-read doesn't have keybindings

### ISSUE THREAD

**Issue by milanst** [DarwinAwardWinner/smex#41]
The default candidate argument to completing-read doesn't have keybindings which causes ido-completing-read+ to display it twice, once with the keybindings and once without. 
This is not a problem with ivy (I haven't tried others) probably because ido-completing-read+ does something different with default argument.
So one could argue that the problem is in ido-completing-read+, but I looked at the source and it seems to me that this is because [this call](https://github.com/DarwinAwardWinner/amx/blob/7fb7b874291e0cdeb1f0acb18564a686ec86788d/amx.el#L308) doesn't pass the bindings hash to the call to amx-augment-command-with-keybind. Adding amx-command-keybind-hash seems to fix my issue but I'm not sure that is the right thing (there must be a reason why bind-hash is optional argument)

**Comment by milanst** [comment]
Just to add, if you turn amx-debug-mode you can see in the messages buffer line with "Got default:" and that has the name of the command without keybindings.

**Comment by DarwinAwardWinner** [comment]
Thanks for reporting this. This is just a simple oversight on my part. I'm pushing a fix to the testing branch, and if it passes all the tests I'll push it to master.

**Comment by milanst** [comment]
Hi, sorry, but this still doesn't fix it. The call to amx-augment-command-with-keybind (line 310 now) still doesn't have bind-hash argument. (I'd make a PR myself but I can't access github from my development machine at the moment).

**Comment by DarwinAwardWinner** [comment]
Oh, whoops, you're right.

**Comment by milanst** [comment]
I made a change by hand to my local amx.el and I can confirm it fixes my issue. Thanks!
