### ISSUE TITLE
truncate minibuffer completions

### ISSUE THREAD

**Issue by jstaursky** [DarwinAwardWinner/smex#42]
could you make a variable available so that minibuffer completions are truncated? currently I need to use
```elisp
(add-hook 'minibuffer-setup-hook
      (lambda () (setq truncate-lines t)))
```
to achieve this effect.

**Comment by DarwinAwardWinner** [comment]
I'm not sure what you mean by truncate. Do you mean that you want the minibuffer limited to a single line?

**Comment by jstaursky** [comment]
Exactly

**Comment by DarwinAwardWinner** [comment]
I'm not sure amx is the right place to do this. Perhaps you could add this function to `ido-minibuffer-setup-hook`? That would do it for all ido completion. If you're using a different backend for amx, you'll have to check if that backend has a similar hook.

**Comment by jstaursky** [comment]
Okay, will do.
