### ISSUE TITLE
Having bindings in candidate conflicts with matching fully typed command.

### ISSUE THREAD

**Issue by okamsn** [DarwinAwardWinner/smex#43]
Hello.

Selectrum has a feature where a fully typed-out candidate (such as the command "man", which I gave a key binding) is automatically selected. However, Amx includes the key bindings in the candidate text, meaning that the command name alone won't fully match the candidate (instead Selectrum only filters to all commands containing "man").

Is there a way to make the keybindings be shown an normal annotations (that is, not part of the candidate itself) at least in some backends, or is that not intended?

Below is what I did to make `amx` work the way I wanted, but it is obviously not a general solution.

Thank you.

```diff
(defun amx-augment-command-with-keybind (command &optional bind-hash)
    "Append COMMAND's key binding to COMMAND.
  
  The key binding is looked up in BIND-HASH. If a binding is not
  found for COMMAND, the command's name is returned alone."
    (let* ((cmdname (amx-get-command-name command))
           (cmdsym (intern cmdname))
           (keybind (and bind-hash (gethash cmdsym bind-hash))))
      (if (and keybind (not (amx-command-ignored-p cmdsym)))
-          (format "%s (%s)" cmdname keybind)
+          (propertize cmdname
+                       'selectrum-candidate-display-suffix
+                       (propertize
+                         (format " (%s)" keybind)
+                         'face 'completions-annotations))
        cmdname)))
```

**Comment by DarwinAwardWinner** [comment]
If I understand correctly, your code will make the binding for each command visible, but won't allow it to complete on those bindings, e.g. if someone types `C-x C-c`, it won't match that to `save-buffers-kill-terminal (C-x C-c)`. Is that correct?

**Comment by okamsn** [comment]
> If I understand correctly, your code will make the binding for each command visible, but won't allow it to complete on those bindings, e.g. if someone types `C-x C-c`, it won't match that to `save-buffers-kill-terminal (C-x C-c)`. Is that correct?

Yes, that is correct. I find it more convenient that way, because of Selectrum's behavior for exact matches. Is there a general way to make the extra information that Amx shows part of an annotation instead of part of the candidate?

For clarity, this is what the Selectrum README.md says:
> If your input matches one of the candidates exactly, then that candidate is unconditionally sorted first. (So, if you type in `find-file`, then `ido-find-file` will never be sorted before `find-file`, no matter what.) This is intended to reduce frustration in the case that you know what you want and you don't want Selectrum getting in the way.

**Comment by DarwinAwardWinner** [comment]
Interesting. I have encountered and fixed this problem before, for standard Emacs completion: 97d35c0d2c8e1ac24043eb280c609999dac7d258

I wonder why this doesn't work for Selectrum.

**Comment by DarwinAwardWinner** [comment]
Ok, I have a guess: selectrum probably isn't using `test-completion` to determine whether an exact match is found. I can explain further later.

**Comment by DarwinAwardWinner** [comment]
Ok, I think Selectrum is probably using `try-completion` or `all-completions` or doing its own equivalent of those, and not using `test-completion`. To demonstrate the difference, see the below:

```elisp
(let* ((table1 '("aaab" "aaac" "aaad"))
       (table2 '("aaa" "bbb" "ccc"))
       (table3 (completion-table-in-turn
                table1
                table2)))
  (list
   (list
    :entry "aaa"
    :table 'table1
    :all-completions (all-completions "aaa" table1)
    :try-completion (try-completion "aaa" table1)
    :test-completion (test-completion "aaa" table1))
   (list
    :entry "aaa"
    :table 'table2
    :all-completions (all-completions "aaa" table2)
    :try-completion (try-completion "aaa" table2)
    :test-completion (test-completion "aaa" table2))
   (list
    :entry "aaa"
    :table 'table3
    :all-completions (all-completions "aaa" table3)
    :try-completion (try-completion "aaa" table3)
    :test-completion (test-completion "aaa" table3))))
```

Which produces:

```elisp
((:entry "aaa"
  :table table1
  :all-completions ("aaab" "aaac" "aaad")
  :try-completion "aaa"
  :test-completion nil)
 (:entry "aaa"
  :table table2 
  :all-completions ("aaa")
  :try-completion t
  :test-completion t)
 (:entry "aaa"
  :table table3
  :all-completions ("aaab" "aaac" "aaad")
  :try-completion "aaa"
  :test-completion t))
```

Note that on table3, `test-completion` returns t, but `try-completion` does not return t and `all-completions` does not return "aaa" as one of the choices. So if you relied only on `all-completions` or `try-completion`, you would conclude that "aaa" was not a valid completion, whereas `test-completion` returns the right answer. The reason for this is because of how `completion-table-in-turn` works: it runs the above functions on each table until it gets a non-nil value, then it returns that value and ignores the remaining tables.

**Comment by DarwinAwardWinner** [comment]
Looking at the selectrum code, it appears that my guess is correct. You might want to report a bug with selectrum indicating that it does not correctly handle collections created by `completion-table-in-turn` and similar functions.

**Comment by okamsn** [comment]
Thank you for the informative answer! I have opened an issue with Selectrum, and will close this issue.

**Comment by DarwinAwardWinner** [comment]
I'm reopening this because I have an idea of how to use your `propertize` solution above while still making it possible to search on the key bindings as well.

**Comment by DarwinAwardWinner** [comment]
Obviously I haven't had time to work on the propertize-based solution to this. I'm going to close this. Hopefully it has been satisfactorily resolved on selectrum's side.
