### ISSUE TITLE
Why only one command history is displayed in Vertico?

### ISSUE THREAD

**Issue by e190** [DarwinAwardWinner/smex#46]
When I use Vertico, I set (setq amx-backend 'auto
only one command history

**Comment by DarwinAwardWinner** [comment]
I'm not familiar with vertico. Can you show a screenshot of the incorrect result, and describe what is wrong?

However, from the vertico README, it appears to be an extension of the Emacs' built in completion system, so can you try `(setq amx-backend 'standard)` and see if that works?

**Comment by e190** [comment]
![图片](https://user-images.githubusercontent.com/39932163/136574545-a69229c6-19cf-4a8c-a546-0bf9fa3fa8ce.png)
No matter how I use the command, only the first one is the history I used, okay

From the second command onwards it was not a command I had used

**Comment by DarwinAwardWinner** [comment]
It appears that the first command is not history, but rather the default, the same item shown in square brackets on the first line (which might simply be the most recent history entry). I will try to find some time to debug this soon.

**Comment by e190** [comment]
The amx configuration has not changed，I have no problem changing the backend to Ivy or Selectrum。

I have checked that amx variables is normal in Vertico
![图片](https://user-images.githubusercontent.com/39932163/136645096-c0fd7857-4dbc-4d8d-8570-26d19e1fc7fc.png)

**Comment by DarwinAwardWinner** [comment]
Hmm, I tested amx with vertico, and as far as I can tell, my full command history is presented at the top of the list starting with the most recently used command. So I'm afraid I can't reproduce this issue.

**Comment by e190** [comment]
You mean you will have no problem using AMX with Vertico? Is there the simplest configuration?

**Comment by DarwinAwardWinner** [comment]
Yes, I simply tried enabling vertico-mode, and it seemed to work correctly, with multiple history items sorted at the top.

**Comment by e190** [comment]
Are you sure there will be a usage history after you restart Emacs?

**Comment by e190** [comment]
my configuration:
`(add-to-list 'load-path "<path-to-vertico>")
(add-to-list 'load-path "<path-to-amx>")
(add-to-list 'load-path "<path-to-s>")
(require 'vertico)
(require 's)
(require 'amx)
(vertico-mode)
(setq amx-mode t)
`

After restart Emacs, there is still no history

**Comment by DarwinAwardWinner** [comment]
Note that `(setq amx-mode t)` is not documented or supported as a way to enable amx mode. The recommended ways are `M-x customize-variable amx-mode` or calling `(amx-mode 1)`.

**Comment by e190** [comment]
I changed it to (amX-mode 1).
After you restart Emacs, there is still no history.
I don't know if it's amX issues or Vertico issues

**Comment by DarwinAwardWinner** [comment]
I am confused. It sounds like you are talking about more than one issue here. Your initial report was about having only one command in the command history. But now you are saying that the problem is that history is not saved when quitting and restarting Emacs? Can you please explain again what specific problem you are having? Can you give a series of steps I can follow to see the problem?

**Comment by e190** [comment]
My problem has always been that I can't show the whole history.
I can confirm that the history has been saved， 
because I see the history command in the amx's cache file (amx-items)

You can write something like this in.emacs files：

(add-to-list 'load-path "<path-to-vertico>") 
(add-to-list 'load-path "<path-to-amx>") 
(add-to-list 'load-path "<path-to-s>") 
(require 'vertico) 
(require 's) 
(require 'amx)
(vertico-mode) 
(amx-mode 1)

**Comment by minad** [comment]
*@e190 asked on the Vertico issue tracker about this (https://github.com/minad/vertico/issues/158). Copying my response here for visibility.*

-----

Amx should not be needed if you use Vertico. Vertico sorts by history position out of the box. If you save the history using savehist-mode, the history will even survive Emacs restarts. Furthermore you may be interested in Marginalia, which adds rich annotations to M-x and many other commands. As far as I can tell, Amx offers no benefits over these features. But I'd be happy to be corrected here.
