### ISSUE TITLE
Ignore `kill-emacs` by default

### ISSUE THREAD

**Issue by doublep** [DarwinAwardWinner/smex#49]
This is not really a bug and also not in AMX, but rather in Emacs itself. Command `kill-emacs` is interactive and thus available to users, but is inherently dangerous, since it doesn't save anything. But it has a "very attractive name", prompting one to use it instead of more user-oriented `save-buffers-kill-emacs`. I'd say it is another instance of bad design in Emacs.

As a workaround, I'd suggest to add it to the default value of `amx-ignored-command-matchers`. Users would still be able to run it if that's *really* what they want by typing in the name fully, or by `M-: (kill-emacs) RET`.

**Comment by DarwinAwardWinner** [comment]
I like this suggestion. Are there any other similarly "dangerous" commands that should be given the same treatment?

**Comment by doublep** [comment]
Not that I know of. I just recently found that out about `kill-emacs`, not that I specifically hunted for "dangerous" commands. I have locally rebound `C-x C-c` for my personal use (why waste a nice shortcut on something needed really rarely?) and have been using `M-x kill-emacs RET` to exit when I do need that. But it is really a bad thing to do, so it would be nice if AMX didn't suggest this for me when typing `M-x killem` (already customized locally).
